language: generic
sudo: required
services:
  - docker
before-install:
  - docker build -t snehaprem04/react-test -f ./client/DockerFile.dev ./client
after_success:
  - docker build -t snehaprem/multi-client ./client
  - docker build -t snehaprem/multi-nginx ./Nginx
  - docker build -t snehaprem/multi-server ./server
  - docker build -t snehaprem/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push into docker hub
  - docker push snehaprem/multi-client
  - docker push snehaprem/multi-nginx
  - docker push snehaprem/multi-server
  - docker push snehaprem/multi-worker