language: generic
sudo: required
services:
  - docker
before-install:
  - docker build -t snehaprem04/react-test -f ./client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true snehaprem04/react-test npm run test
after_success:
  - docker build -t snehaprem04/multi-client ./client
  - docker build -t snehaprem04/multi-nginx ./nginx
  - docker build -t snehaprem04/multi-server ./server
  - docker build -t snehaprem04/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push into docker hub
  - docker push snehaprem04/multi-client
  - docker push snehaprem04/multi-nginx
  - docker push snehaprem04/multi-server
  - docker push snehaprem04/multi-worker